runtime: python37

#api_version: 2
#entrypoint: gunicorn -b :$PORT dash_test.wsgi:application
#instance_class: F2
handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /assets
  static_dir: viz/assets
# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
######test app.yaml entrypoint
#- url: .*
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1800

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 3600

manual_scaling:
  instances: 5
